### ISSUE TITLE
Homebrew 2.3.0 has broken this ansible role

### ISSUE THREAD

**Issue by filipVisko** [azavea/ansible-buildkite-agent#38] opened 2020-06-03 14:44 UTC
A freshly installed macOS catalina with homebrew is unable to install buildkite agent.

```
    default: TASK [ansible-buildkite-agent : Install buildkite-agent] ***********************
    default: Wednesday 03 June 2020  14:46:42 +0100 (0:00:00.658)       0:03:35.932 ********
    default: fatal: [127.0.0.1]: FAILED! => changed=false
    default:   msg: |-
    default:     fatal: Could not resolve HEAD to a revision
    default:     Error: An exception occurred within a child process:
    default:       NoMethodError: undefined method `value' for #<Array:0x00007fe591884040>
    default:     Did you mean?  values_at
    default:
    default: PLAY RECAP *********************************************************************
```

Versions of Brew and Ruby:
```
Homebrew 2.3.0
Homebrew/homebrew-core (git revision bbc1e; last commit 2020-06-03)
Homebrew/homebrew-cask (git revision 05fcf1f; last commit 2020-06-03)
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

**Comment by bombsimon** [comment] 2020-09-17 17:55
I just installed a machine with macOS Catalina 10.15.6 and latest Homebrew 2.5.1 today and I could not reproduce this issue.

**Comment by petemounce** [comment] 2020-09-17 22:59
@bombsimon thanks very much; I have not been able to reproduce either.

@filipVisko I'll close this for now; please ping if you have more information?

**Closed as completed by petemounce** 2020-09-17 22:59 UTC
